### ISSUE TITLE
Typo in anatomical entity comment?

### ISSUE THREAD

**Issue by ukemi** [geneontology/GO_Shapes#21]
<AnatomicalEntity> @<GoCamEntity> AND {
   bl:category [GoAnatomicalEntity:]  ;
}// rdfs:comment "a chemical entity"

should be

<AnatomicalEntity> @<GoCamEntity> AND {
   bl:category [GoAnatomicalEntity:]  ;
}// rdfs:comment "an anatomical entity"

**Comment by goodb** [comment]
yup.  will resolve in next commit.
