### ISSUE TITLE
Incorrect label RO_0002413

### ISSUE THREAD

**Issue by pgaudet** [geneontology/GO_Shapes#32]
provides_direct_input_for: 
For <http://purl.obolibrary.org/obo/RO_0002413>  we have label 'provides_direct_input_for'

But in RO and in Noctua it is 'directly provides input for (process to process)' 

1. Should we change the relation in the specs ? 
2. The specs state: directly_provides_input_for: @<MolecularFunction- this is inconsistent with the `process to process` part of the term label. 

Seems like something should be changed somewhere ... ? 

Thanks, Pascale

**Comment by balhoff** [comment]
> this is inconsistent with the process to process part of the term label.

I think this is BFO:process, so it is okay for MolecularFunction.

**Comment by pgaudet** [comment]
Thanks for the clarification.

**Comment by vanaukenk** [comment]
Ben addressed this in #28
